triggering:
  events:                       # List the events that trigger builds
    - push
workflows:
  hello-world:
    name: Hello world workflow
    scripts:
        - ./npm
        - ls
        - echo  29447 

