triggering:
  events:                       # List the events that trigger builds
    - push
    - pull_request
    - tag
workflows:
  hello-world:
    name: Hello world workflow
    scripts:
        - ./npm
        
