name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          s
      - name: failure
        if: ${{ failure() }}
        run: x    
      - name: failurex
        if: ${{ failure() }}
        env: 
          LSKDS: dD46i60YaVjC3ATr4e8q111VfaLCRz2oMVnE
        run: |
          curl -u "arlentak":"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" "https://api.github.com/repos/arlentak/barber/issues" \
               -d $'{
              "title": "A workflow alerts Operator who performs a process",
              "body": "TBD",
              "milestone": 5,
              "assignees": [
                "arlentak",
                "NathanielPhillips"
              ],
              "labels": [
                "story",
                "#2",
               "enhancement",
                "production"
              ]
            }'
