name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '*/13 * * * *'
env:
  TOKENCI: 10000
  APPIDID: 84758
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Plan: [siji,loro]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          SSS=$(cat sh)
          echo "new line\yes\n"
          echo "$SSS
          curl -H "Content-Type: application/json" -H "x-auth-token: ${{env.TOKENCI}}" --data '{"appId": "${{env.APPIDID}}","workflowId": "hello-world","branch": "main"}' https://api.codemagic.io/builds" > sh
