name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '*/13 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Plan: [siji,loro]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          SSS=$(cat sh)
          echo "new line\yes\n"
          echo "$SSS"
