name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          s
      - name: failure
        if: ${{ failure() }}
        run: x    
      - name: failurex
        if: ${{ failure() }}
        run: |
          curl -X "POST" "https://api.github.com/repos/rickcogley/RCC-Hugo2015/issues?state=all" \
               -H "Cookie: logged_in=no" \
               -H "Authorization: token THEd13GITHUBfb87TOKENa4FROM5eSETTINGS" \
               -H "Content-Type: text/plain; charset=utf-8" \
               -d $'{
            "title": "A workflow alerts Operator who performs a process",
            "body": "TBD",
            "milestone": 5,
            "assignees": [
              "RickCogley",
              "NathanielPhillips"
            ],
            "labels": [
              "story",
              "#2",
              "enhancement",
              "production"
            ]
          }'
