name: Mac OS Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          sleep 20s
      - run: brew tap buildkite/buildkite
      - run:     brew install buildkite-agent
          
      - run:     TOKEN="9fb32670b052083cc189d3235934cdf05a92d42cff84f0b541"
      - run:     sudo sed -i "s/xxx/9fb32670b052083cc189d3235934cdf05a92d42cff84f0b541/g" /etc/buildkite-agent/buildkite-agent.cfg

