name: Mac OS Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: TOKEN="9fb32670b052083cc189d3235934cdf05a92d42cff84f0b541" bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/master/install.sh`"
      - run: ~/.buildkite-agent/bin/buildkite-agent start


